version: "3.7"

services:
  mysql:
    container_name: mysql
    image: mysql:5.5.62
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./sql/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql